M48
; DRILL file KiCad 10.0.1 date 2026-07-04T03:36:32
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-04T03:36:32-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X115.76Y-125.145
X121.54Y-125.145
T2
X81.5Y-128.25
M30
